In [31]:
import numpy as np
import pandas as pd

from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

In [12]:
data = np.genfromtxt('data/matrix.txt', delimiter=';')
data.shape

(300, 7677)

In [34]:
x_data, y_data = data[:, :7676], data[:, 7676]

In [40]:
def calc_values(y_data, y_pred):
    tp, fp, tn, fn = 0, 0, 0, 0
    for d, p in zip(y_data, y_pred):
        if d == 1 and d == p:
            tp += 1
        if d == 1 and d != p:
            fn += 1
        if d == 0 and d == p:
            tn += 1
        if d == 0 and d != p:
            fp += 1
    return tp, fp, tn, fn

In [47]:
unique, counts = np.unique(y_data, return_counts=True)
print(dict(zip(unique, counts)))

{0.0: 200, 1.0: 100}


In [48]:
est_gb = GradientBoostingClassifier()
est_gb.fit(x_data, y_data)

y_pred_gb = est_gb.predict(x_data)
print('Accuracy: %f' % accuracy_score(y_data, y_pred_gb))
print(precision_recall_fscore_support(y_data, y_pred_gb))
print('tp: %f\nfp: %f\ntn: %f\nfn: %f' % calc_values(y_data, y_pred_gb))

Accuracy: 0.910000
(array([ 0.88105727,  1.        ]), array([ 1.  ,  0.73]), array([ 0.93676815,  0.84393064]), array([200, 100]))
tp: 73.000000
fp: 0.000000
tn: 200.000000
fn: 27.000000


In [49]:
est_rf = RandomForestClassifier()
est_rf.fit(x_data, y_data)

y_pred_rf = est_rb.predict(x_data)
print('Accuracy: %f' % accuracy_score(y_data, y_pred_rf))
print(precision_recall_fscore_support(y_data, y_pred_rf))
print('tp: %f\nfp: %f\ntn: %f\nfn: %f' % calc_values(y_data, y_pred_rf))

Accuracy: 0.903333
(array([ 0.87336245,  1.        ]), array([ 1.  ,  0.71]), array([ 0.93240093,  0.83040936]), array([200, 100]))
tp: 71.000000
fp: 0.000000
tn: 200.000000
fn: 29.000000


In [50]:
est_mnb = MultinomialNB()
est_mnb.fit(x_data, y_data)

y_pred_mnb = est_mnb.predict(x_data)
print('Accuracy: %f' % accuracy_score(y_data, y_pred_mnb))
print(precision_recall_fscore_support(y_data, y_pred_mnb))
print('tp: %f\nfp: %f\ntn: %f\nfn: %f' % calc_values(y_data, y_pred_mnb))

Accuracy: 0.760000
(array([ 0.73529412,  1.        ]), array([ 1.  ,  0.28]), array([ 0.84745763,  0.4375    ]), array([200, 100]))
tp: 28.000000
fp: 0.000000
tn: 200.000000
fn: 72.000000
